App\Entities\SpeechActions:
    type: entity
    table: dngo_speech_actions
    repositoryClass: App\Repositories\SpeechRepository

    id:
        id:
            type: integer
            generator:
                strategy: auto
            options:
                unsigned: true

    fields:
        do:
          type: string
          length: 255

        action:
          type: string
          length: 10

        error:
          type: string
          length: 255

        sort:
          type: integer
          options:
            default:  0

    manyToOne:
        parent:
          targetEntity: App\Entities\Speech