App\Entities\Crawler:
    type: entity
    table: crawler
    repositoryClass: App\Repositories\CrawlerRepository

    indexes:
        idx_identifier:
            columns: [ identifier ]
        idx_sttaus:
            columns: [ status ]
        idx_source:
            columns: [ source ]

    id:
        id:
            type: integer
            generator:
                strategy: auto
            options:

    fields:
        url:
          type: string

        identifier:
          type: string

        status:
          type: string
          length: 50

        source:
          type: string
